version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  web:
    build: .
    command: ["sh", "-c", "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 8532 -b '0.0.0.0'"]
    volumes:
      - .:/var/www/EquipmentCheckoutSystem
    ports:
      - "8532:8532"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: mysecretpassword  # Added to match the database.yml
      # RAILS_ENV: production
      # RACK_ENV: production
      RAILS_ENV: development #=> Change this to development
      RACK_ENV: development  #=> Change this to development
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db:5432/EquipmentCheckoutSystem_development"

volumes:
  postgres_data: